[package]
name = "edgefirst-decoder"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[features]
default = ["tracker"]
tracker = ["dep:edgefirst-tracker"]

[dependencies]
argminmax = { version = "0.6.3", default-features = false}
edgefirst-tracker = { version = "*", path = "../tracker", optional=true }
env_logger = { workspace = true }
fast-math = "0.1.1"
log = { workspace = true }
ndarray = { workspace = true }
ndarray-stats = "0.6.0"
num-traits.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml = "0.9.34"


[dev-dependencies]
divan = { workspace = true }
image = { version = "0.25.6", default-features = false, features = ["png"]}


[[bench]]
name = "decoder_benchmark"
harness = false
