[package]
name = "edgefirst-decoder"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
edgefirst-tensor = { version = "*", path = "../tensor" }
env_logger = { workspace = true }
log = { workspace = true }
ndarray = { workspace = true }
num-traits.workspace = true

[dev-dependencies]
divan = { workspace = true }
image = { version = "0.25.6", default-features = false, features = ["png"]}


[[bench]]
name = "decoder_benchmark"
harness = false
