[package]
name = "edgefirst-python"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = []
python-abi38 = ["pyo3/abi3-py38"]
python-abi311 = ["pyo3/abi3-py311"]

[dependencies]
edgefirst = { version = "*", path = "../edgefirst" }
env_logger = { workspace = true }
four-char-code = { workspace = true }
pyo3 = { version = "0.25.1", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = { version = "0.25.1", features = ["resolve-config"] }
