[package]
name = "edgefirst-hal-python"
description = "Low-level FFI bindings for the G2D Library"
license = "MIT"
version = "1.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = []
python-abi38 = ["pyo3/abi3-py38"]
python-abi311 = ["pyo3/abi3-py311"]

[dependencies]
env_logger = { workspace = true }
pyo3 = { version = "0.25.1", features = ["extension-module"] }
tensor = { path = "../tensor" }

[build-dependencies]
pyo3-build-config = { version = "0.25.1", features = ["resolve-config"] }
