[package]
name = "edgefirst_hal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["extension-module"]
python-abi38 = ["pyo3/abi3-py38"]
python-abi311 = ["pyo3/abi3-py311"]
extension-module = ["pyo3/extension-module"]

[dependencies]
edgefirst = { workspace = true }
env_logger = { workspace = true }
four-char-code = { workspace = true }
half = { workspace = true }
log = { workspace = true }
ndarray = { workspace = true }
numpy = { workspace = true }
pyo3 = { workspace = true }
pythonize = { workspace = true }

[build-dependencies]
pyo3-build-config = { workspace = true }
rustc_version = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
