[package]
name = "edgefirst_hal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["extension-module"]
python-abi38 = ["pyo3/abi3-py38"]
python-abi311 = ["pyo3/abi3-py311"]
extension-module = ["pyo3/extension-module"]

[dependencies]
edgefirst = { version = "*", path = "../edgefirst" }
env_logger = { workspace = true }
four-char-code = { workspace = true }
numpy = { version = "0.26.0", features = ["half"] }
pyo3 = { version = "0.26.0" }
ndarray = { workspace = true }
pythonize = "0.26.0"
half = "2.7.1"
log = { workspace = true }

[build-dependencies]
pyo3-build-config = { version = "0.26.0", features = ["resolve-config"] }
rustc_version = "0.4"

[dev-dependencies]
approx = "0.5.1"
