[package]
name = "edgefirst_python"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["extension-module"]
python-abi38 = ["pyo3/abi3-py38"]
python-abi311 = ["pyo3/abi3-py311"]
extension-module = ["pyo3/extension-module"]

[dependencies]
edgefirst = { version = "*", path = "../edgefirst" }
env_logger = { workspace = true }
four-char-code = { workspace = true }
numpy = "0.25.0"
pyo3 = { version = "0.25.1" }
ndarray = { workspace = true }
pythonize = "0.25.0"

[build-dependencies]
pyo3-build-config = { version = "0.25.1", features = ["resolve-config"] }

[dev-dependencies]
approx = "0.5.1"
