[package]
name = "edgefirst-image"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
ctor = { workspace = true }
env_logger = { workspace = true }
fast_image_resize = { workspace = true }
four-char-code = { workspace = true }
jpeg-encoder = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
edgefirst-tensor = { version = "*", path = "../tensor" }
zune-jpeg = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
dma-heap = { workspace = true }
g2d-sys = { version = "*", path = "../g2d-sys" }

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "image_benchmark"
harness = false
